version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: vibesyncpass
      MYSQL_DATABASE: vibesyncdb
      MYSQL_USER: vibesyncuser
      MYSQL_PASSWORD: vibesyncpass
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
volumes:
  mysql-data:
